DROP DATABASE IF EXISTS employees;
CREATE DATABASE employees;

USE employees;

CREATE TABLE department (
  -- CREATE id, name COLUMNS
  -- MAKE id AS PRIMARY KEY
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
  -- TODO: YOUR CODE HERE

);

CREATE TABLE role (
  -- CREATE id AS INTERGER
  -- MAKE id As PRIMARY KEY
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  --title AS VARCHAR
  title VARCHAR(50) NOT NULL,
  --salary AS DECIMAL
  salary DECIMAL NOT NULL, 
  --deplartment_id AS INTEGER
  department_id INT NOT NULL,
  -- MAKE department_id AS FOREIGN KEY 
  FOREIGN KEY(department_id)
  --REFERENCING department TABLE
  REFERENCES department(id)
  -- MAKE CONSTRAINT 'ON DELETE CASCADE'
  ON DELETE CASCADE

);

CREATE TABLE employee (
  -- CREATE id AS INT 
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  -- MAKE id As PRIMARY KEY
  --first_name AS VARCHAR 
  first_name VARCHAR(20),
  --last_name AS VARCHAR 
  last_name VARCHAR(40),
  --role_id AS INTEGER 
  role_id INT NOT NULL,
  -- MAKE role_id AS FOREIGN KEY REFERENCING role TABLE AND MAKE CONSTRAINT ON DELETE CASCADE ON THIS FOREIGN KEY
  FOREIGN KEY (role_id)
  REFERENCES role(id)
  ON DELETE CASCADE
  --manager_id AS INT.
  manager_id INT NOT NULL,
  -- MAKE manager_id AS FOREIGN KEY REFERENCING employee TABLE ITSELF AND MAKE CONSTRAINT ON DELETE SET NULL ON THIS FOREIGN KEY
  FOREIGN KEY(manager_id)
  REFERENCES employe(id)
  ON DELETE SET NULL
  

);
